make serve work on windows

diff --git a/serve b/serve
--- a/serve
+++ b/serve
@@ -1,54 +1,21 @@
 #!/usr/bin/env bash
 set -e errexit
 
-toolsDir=$(dirname ${0})
-wwwDir="${toolsDir}/../www.gothicarchive.org"
 
-if [[ ! -e "${wwwDir}" ]]; then
-  echo "can't find ${wwwDir}" >&2
-  exit 1
-fi
 
 if [[ ! -e "_config.yml" ]]; then
+  toolsDir=$(dirname "${0}")
+  wwwDir="${toolsDir}/../www.gothicarchive.org"
+
+  if [[ ! -e "${wwwDir}" ]]; then
+    echo "can't find ${wwwDir}" >&2
+    exit 1
+  fi
+  
   cd "${wwwDir}"
 fi
 
+export JEKYLL_ENV=development
+
 set -x
-subRepositories=( audio bin images videos )
-
-# prepare symlinks
-for repository in "${subRepositories[@]}"
-do
-  if [[ -e "${repository}/.git" ]]; then
-    continue # already cloned
-  fi
-  if [[ ! -e "../${repository}.gothicarchive.org/.git" ]]
-  then
-      echo "do recursive clone with submodules first" >&2
-      exit 1
-  fi
-  export MSYS="winsymlinks:nativestrict"
-  ln -s "../${repository}.gothicarchive.org" "${repository}"
-done
-
-# stop spawned jekyll process on script exit
-trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
-
-# start jekyll in background
-JEKYLL_ENV=development bundle exec jekyll serve --port 4420 &
-
-# keep recreating the symlink that jekyll removes on some updates
-while :
-do
-  if [[ ! -e "_site" ]]; then
-    mkdir "_site"
-  fi
-  for repository in "${subRepositories[@]}"
-  do
-    if [[ ! -e "_site/${repository}" ]]
-    then
-        ln -s "${PWD}/${repository}" "_site/${repository}"
-    fi
-  done
-  sleep 5
-done
+bundle exec jekyll serve --port 4420
